### ISSUE TITLE
Change module & package name

### ISSUE THREAD

**Issue by overheadhunter** [purejava/appindicator-gtk3-java#3]
As mentioned in [my PR review](https://github.com/cryptomator/cryptomator/pull/2862#discussion_r1166679549), I would suggest that you choose a module _and_ package name that fulfil these requirements:

1. use a reverse domain name package name for a domain that is under your control ✔️ 
2. use a root package name that will *never* be used by *any* other module ✖️ 
3. [bonus: use a module name that matches the begin of your root package] ✖️ 

https://github.com/purejava/libappindicator-gtk3-java/blob/9fef3b1976c03eb0040556b7f62ac98098ea165a/src/main/java/module-info.java#L1-L4

Should you ever want to publish another module for some linux lib binding, you can not use `org.purejava.linux.*` any longer. This name is now forever taken by _this_ library. Otherwise library consumers would run into a split package problem, preventing them from using your libs in a modular app.

Therefore I suggest to change the names to e.g.

```java
module org.purejava.libappindicator.full { 
    requires org.slf4j; 
    exports org.purejava.libappindicator; // technically still a problem if you include "full" and "minimal" jars at the same time!
} 
```

**Comment by overheadhunter** [comment]
On second thought I would use the same module name for all build variants. It is the dependency manager's job to make sure you don't include `full` and `minimal` at the same time.

Either use a version suffix (`1.2.0-minimal`) or a `<classifier>`.

**Comment by purejava** [comment]
Hey @overheadhunter, thank you very much for bringing this up again!
As you might have noticed, this is the first time I defined Java module and package names and so do not have any experience in this.

Thanks for the hints and the example on how to do it right. I'll change the names as suggested.

**Comment by purejava** [comment]
Fixed by https://github.com/purejava/appindicator-gtk3-java/commit/d49a25372d025c6fffd8b96fea74f55ef42922a3, https://github.com/purejava/appindicator-gtk3-java/commit/a39040c57faadd1ef2af6fa9e244fb1ad12c8e92 and https://github.com/purejava/appindicator-gtk3-java/commit/8207b706d6449ddafbcc562bd3ee8243c33a5c87.
