### ISSUE TITLE
JDK 22 Support

### ISSUE THREAD

**Issue by overheadhunter** [purejava/appindicator-gtk3-java#36]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/appindicator-gtk3-java/issues?q=) for duplicates

### Summary

Build the project with/for JDK 22

### Motivation

see #14 😉

### Anything else?

Starting with JDK 22, this is no longer a preview feature and this should be the last urgent JDK bump.

**Comment by purejava** [comment]
It's interesting, that the Foreign Function & Memory API has that big changes from Java 21 to Java 22, where it is supposed to no longer be a preview feature, as the changes from 19 to 21 were much lesser.

**Comment by overheadhunter** [comment]
The FFM API itself didn't change _that_ much, however jextract is now really gaining pace.

Since you mostly exposed jextract'ed classes directly, lib users will see a huge diff. What I recommend instead is to create your own stable high-level API which is to be consumed by downstream users. Then hide the jextract'ed code behind the public API, basically implementing the facade pattern.

**Comment by purejava** [comment]
> The FFM API itself didn't change _that_ much, however jextract is now really gaining pace.
> 

You are right. Taking a deeper look brought me to the same conclusion.

> Since you mostly exposed jextract'ed classes directly, lib users will see a huge diff. What I recommend instead is to create your own stable high-level API which is to be consumed by downstream users. Then hide the jextract'ed code behind the public API, basically implementing the facade pattern.

Done. Public API is tested, is working and prepared as a [ready-to-merge branch](https://github.com/purejava/integrations-linux/commit/cfd25392ee7c263ae5ed51d59beb66251d019b9d) for `integrations-linux`, once Java 22 has been released.

**Comment by infeo** [comment]
Since you already released an artifact build with JDK 22, i think this issue can already be closed 😉 All other changes are downstream in consumer libs.

**Comment by purejava** [comment]
> Since you already released an artifact build with JDK 22, i think this issue can already be closed 😉 All other changes are downstream in consumer libs.

I am lazy. 😉 https://github.com/cryptomator/integrations-linux/pull/69 has all the necessary changes for `integrations-linux` and closes this issue automatically, once merged.
